services:
  mongo:
    image: mongo:7
    container_name: mongo_local
    restart: unless-stopped
    command: --bind_ip_all
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - '27018:27017'
    volumes:
      - mongo_local_data:/data/db

  redis:
    image: redis:7
    container_name: redis_local
    command: sh /usr/local/bin/init-redis.sh
    environment:
      - SPRING_REDIS_USER=${SPRING_REDIS_USER}
      - SPRING_REDIS_PASSWORD=${SPRING_REDIS_PASSWORD}
    ports:
      - '6379:6379'
    volumes:
      - redis_local_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - ./init-redis.sh:/usr/local/bin/init-redis.sh

  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: cineclub_backend_local
    depends_on:
      - mongo
      - redis
    env_file:
      - .env
    environment:
      - SPRING_DEVTOOLS_RESTART_ENABLED=true
    ports:
      - '${APP_PORT:-8080}:8080'
    volumes:
      - .:/app
    command: ['./mvnw', 'spring-boot:run']

volumes:
  mongo_local_data:
  redis_local_data:
