name: Keep Alive

on:
  #schedule:
  #  - cron: '*/14 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Health Endpoint
        run: curl -I https://cineclub-back.onrender.com/health
